name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9.20"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Cache
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install
        run: poetry install
      - name: Lint
        run: poetry run flake8 --exit-zero
      - name: Test
        run: poetry run pytest -v --cov --cov-report term-missing